import { StyleSheet } from 'react-native';

import type { ThemeColors } from '../../../lib/theme';

export type SignupStyles = ReturnType<typeof createSignupStyles>;

export function createSignupStyles(colors: ThemeColors, isDark: boolean) {
  const surface = colors.surface;
  const surfaceAlt = colors.surfaceSecondary;
  const accent = colors.accent;
  const text = colors.text;
  const muted = colors.muted;
  const border = colors.border;

  return StyleSheet.create({
    /* BACKGROUND */
    background: { flex: 1, backgroundColor: colors.background },
    backgroundImage: { resizeMode: 'cover' },
    scrim: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: isDark ? 'rgba(6, 9, 20, 0.6)' : 'rgba(255,255,255,0.65)',
    },
    shell: { padding: 24, gap: 24, minHeight: '100%', flexGrow: 1 },
    shellWide: { flexDirection: 'row', alignItems: 'stretch' },
    shellNarrow: { padding: 0, gap: 0, justifyContent: 'center' },

    /* LEFT HERO */
    leftPane: {
      flex: 1.2,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: border,
      overflow: 'hidden',
    },
    leftPaneWide: { minHeight: 680, maxHeight: 680 },
    leftPaneStatic: { alignSelf: 'flex-start' },
    leftPaneNarrow: { minHeight: 420 },
    leftBackground: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: 32,
      paddingVertical: 0,
    },
    leftBackgroundImage: {
      resizeMode: 'cover',
      width: '100%',
      height: '100%',
    },
    leftOverlay: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: isDark ? 'rgba(10, 14, 26, 0.55)' : 'rgba(255,255,255,0.45)',
    },
    leftContent: {
      flex: 1,
      gap: 16,
      padding: 28,
      paddingTop: 32,
      alignSelf: 'stretch',
    },
    leftCopy: {
      flex: 1,
      justifyContent: 'center',
      gap: 16,
    },
    brandRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      gap: 12,
    },
    logoImg: { width: 96, height: 96, borderRadius: 24, borderWidth: 1, borderColor: border },
    brand: { color: text, fontSize: 24, fontWeight: '800' },
    brandSub: { color: muted, fontSize: 12, marginTop: 2, letterSpacing: 1 },
    tagline: { color: text, fontSize: 24, lineHeight: 32, fontWeight: '700' },
    subTagline: { color: muted, fontSize: 14, lineHeight: 20 },
    quote: { color: muted, fontSize: 13, lineHeight: 18, maxWidth: 220 },
    leftHeroArt: {
      width: '115%',
      height: 320,
      alignSelf: 'center',
      marginTop: 8,
      opacity: 0.9,
    },

    /* RIGHT PANE CARD */
    rightPane: { flex: 0.8, minWidth: 320 },
    card: {
      borderRadius: 28,
      backgroundColor: surface,
      padding: 28,
      borderWidth: 1,
      borderColor: border,
      minHeight: 560,
      position: 'relative',
      overflow: 'hidden',
    },
    cardTitle: {
      color: text,
      fontSize: 30,
      fontFamily: 'PlayfairDisplay_400Regular',
      fontWeight: '800',
      textAlign: 'center',
    },
    cardSubtitle: { color: muted, fontSize: 14, textAlign: 'center', marginTop: 4, marginBottom: 20 },
    stepLabel: { color: muted, fontSize: 13, fontWeight: '600', marginBottom: 12 },
    stepLabelMobile: { textAlign: 'center', marginBottom: 14 },
    accordionStack: { gap: 10 },
    accordionBlock: { borderRadius: 20, gap: 12, padding: 4 },
    accordionBlockActive: {
      backgroundColor: surfaceAlt,
      borderWidth: 1,
      borderColor: border,
      padding: 12,
      shadowColor: accent,
      shadowOpacity: 0.12,
      shadowRadius: 16,
      shadowOffset: { width: 0, height: 10 },
    },
    accordionHeader: {
      minHeight: 56,
      borderRadius: 22,
      borderWidth: 1.5,
      borderColor: accent,
      backgroundColor: surfaceAlt,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      paddingHorizontal: 20,
    },
    accordionLabel: { fontSize: 16, fontWeight: '600', color: text },
    accordionBody: { marginTop: 6 },
    methodChevron: { marginLeft: 'auto' },

    /* FORM */
    formCard: {
      marginTop: 18,
      borderRadius: 22,
      padding: 22,
      backgroundColor: surface,
      borderWidth: 1,
      borderColor: border,
      gap: 16,
    },
    formTitle: { color: text, fontSize: 18, fontWeight: '700' },
    formHint: { color: muted, fontSize: 13, lineHeight: 20 },
    recaptchaWrapper: {
      alignSelf: 'flex-start',
      padding: 6,
      borderRadius: 12,
      backgroundColor: surfaceAlt,
      borderWidth: 1,
      borderColor: border,
    },
    formGrid: { gap: 18 },
    inputGroup: { gap: 6 },
    label: { color: text, fontSize: 13, fontWeight: '600' },

    input: {
      height: 52,
      borderRadius: 16,
      backgroundColor: colors.inputBackground,
      paddingHorizontal: 18,
      color: text,
      borderWidth: 1,
      borderColor: border,
    },
    inputRow: {
      height: 52,
      borderRadius: 16,
      backgroundColor: colors.inputBackground,
      paddingHorizontal: 18,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 12,
      borderWidth: 1,
      borderColor: border,
    },
    inputField: { flex: 1, height: 52, color: text },

    validationPanel: {
      borderRadius: 16,
      padding: 16,
      backgroundColor: surfaceAlt,
      borderWidth: 1,
      borderColor: border,
      gap: 10,
    },
    validationTitle: { color: muted, fontSize: 13, fontWeight: '600', letterSpacing: 1 },
    validationRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
    validationText: { color: colors.subtle, fontSize: 13 },
    validationTextPassed: { color: colors.success },

    checkboxRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    checkbox: {
      width: 22,
      height: 22,
      borderRadius: 6,
      borderWidth: 1,
      borderColor: border,
      alignItems: 'center',
      justifyContent: 'center',
      backgroundColor: surfaceAlt,
    },
    checkboxChecked: { backgroundColor: accent, borderColor: accent },
    checkboxLabel: { color: text, flex: 1, fontSize: 13 },
    linkText: { color: accent, textDecorationLine: 'underline', fontWeight: '600' },

    primaryButton: {
      height: 52,
      borderRadius: 16,
      backgroundColor: accent,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      gap: 12,
    },
    primaryButtonText: { fontSize: 16, fontWeight: '700', color: isDark ? colors.text : '#0f172a' },
    submitDisabled: { backgroundColor: surfaceAlt, borderColor: border },
    submitButton: { marginTop: 8, alignSelf: 'stretch', width: '100%' },

    errorBanner: {
      marginTop: 16,
      flexDirection: 'row',
      alignItems: 'center',
      gap: 8,
      padding: 12,
      borderRadius: 12,
      backgroundColor: isDark ? 'rgba(248,113,113,0.12)' : 'rgba(248,113,113,0.08)',
      borderWidth: 1,
      borderColor: colors.danger,
    },
    errorText: { color: colors.danger, fontSize: 13, flex: 1 },

    footerHint: { color: muted, fontSize: 13, textAlign: 'center', marginTop: 16 },
    altRouteRow: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8, marginTop: 4 },
    altRouteText: { color: muted, fontSize: 14 },
    altRouteLink: { color: accent, fontSize: 14, fontWeight: '600' },

    successCard: {
      borderRadius: 16,
      padding: 20,
      gap: 12,
      backgroundColor: surfaceAlt,
      borderWidth: 1,
      borderColor: colors.success,
    },
    successTitle: { color: text, fontSize: 20, fontWeight: '700' },
    successCopy: { color: text, fontSize: 14, lineHeight: 20 },
    successWarn: { color: colors.warning, fontSize: 13 },
    successActions: { flexDirection: 'row', gap: 16, flexWrap: 'wrap' },
    primaryLink: { color: accent, fontWeight: '700', fontSize: 16 },
    secondaryLink: { color: colors.accent, fontWeight: '600', fontSize: 15 },

    /* HERO MARIO + GLOSS */
    glossBox: {
      position: 'absolute',
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
      borderRadius: 24,
      borderWidth: 1,
      borderColor: border,
      pointerEvents: 'none',
    },
    cardMobile: {
      flex: 1,
      borderRadius: 0,
      backgroundColor: surface,
      padding: 24,
      borderWidth: 0,
      shadowOpacity: 0,
      shadowRadius: 0,
      shadowOffset: { width: 0, height: 0 },
      elevation: 0,
      gap: 12,
      minHeight: '100%',
    },
    mobileCardWrapper: { flex: 1, width: '100%', alignSelf: 'stretch' },
    mobileBrandRow: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginBottom: 4,
    },
    mobileBrandLeft: { flexDirection: 'row', alignItems: 'center', gap: 12 },
    mobileLogoMark: {
      width: 52,
      height: 52,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: border,
    },
    mobileBrand: { color: text, fontSize: 22, fontWeight: '800' },
    mobileBrandMeta: { color: muted, fontSize: 12 },
    mobileCloseBtn: {
      width: 42,
      height: 42,
      borderRadius: 21,
      borderWidth: 1,
      borderColor: border,
      backgroundColor: surfaceAlt,
      alignItems: 'center',
      justifyContent: 'center',
    },
    mobileTagline: { color: muted, textAlign: 'center', fontSize: 14, marginBottom: 10 },
    mobilePanelHeader: { alignItems: 'center' },
    mobileCharactersImg: { width: '100%', height: 170 },
    mobilePanel: {
      borderRadius: 28,
      borderWidth: 1,
      borderColor: border,
      padding: 22,
      gap: 12,
      backgroundColor: surfaceAlt,
    },
    mobileFooterTextBlock: { alignItems: 'center', gap: 4 },
    mobileFooterText: { color: muted, fontSize: 13 },
    mobileGlossBox: { borderRadius: 0, borderColor: border },
    homeLink: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 4 },
    homeText: { color: accent, fontWeight: '600' },
    mobileFullBackground: { padding: 0 },

    /* GOOGLE INLINE (mobile) */
    inlineGoogleCard: {
      gap: 12,
      borderRadius: 18,
      backgroundColor: surface,
      padding: 18,
      borderWidth: 1,
      borderColor: border,
    },
    inlineGoogleHint: { color: muted, fontSize: 14 },
    inlineGoogleButton: {
      minHeight: 60,
      borderRadius: 20,
      borderWidth: 1.5,
      borderColor: border,
      backgroundColor: surfaceAlt,
      flexDirection: 'row',
      alignItems: 'center',
      paddingHorizontal: 20,
      gap: 14,
    },
    inlineGoogleText: { fontSize: 17, fontWeight: '700', color: text },
  });
}
