const BILLING_URL = process.env.EXPO_PUBLIC_BILLING_URL;
const STRIPE_PUBLISHABLE_KEY = process.env.EXPO_PUBLIC_STRIPE_PUBLISHABLE_KEY;
const MODERATION_URL = process.env.EXPO_PUBLIC_MODERATION_URL;

export { BILLING_URL, STRIPE_PUBLISHABLE_KEY, MODERATION_URL };
