import { StyleSheet } from 'react-native';

export const signupStyles = StyleSheet.create({
  background: { flex: 1 },
  backgroundImage: { resizeMode: 'cover' },
  scrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(6, 9, 20, 0.6)',
  },
  shell: { padding: 24, gap: 24, minHeight: '100%', flexGrow: 1 },
  shellWide: { flexDirection: 'row', alignItems: 'stretch' },

  leftPane: {
    flex: 1.2,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(99,102,241,0.35)',
    overflow: 'hidden',
  },
  leftPaneWide: { minHeight: 680, maxHeight: 680 },
  leftPaneStatic: { alignSelf: 'flex-start' },
  leftPaneNarrow: { minHeight: 420 },
  leftBackground: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 32,
    paddingVertical: 0,
  },
  leftBackgroundImage: {
    resizeMode: 'cover',
    width: '100%',
    height: '100%',
  },
  leftOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(10, 14, 26, 0.55)',
  },
  leftContent: {
    flex: 1,
    gap: 16,
    padding: 28,
    paddingTop: 32,
    alignSelf: 'stretch',
  },
  leftCopy: {
    flex: 1,
    justifyContent: 'center',
    gap: 16,
  },
  brandRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'flex-start',
    gap: 12,
  },
  logoImg: { width: 96, height: 96, borderRadius: 24, borderWidth: 1, borderColor: 'rgba(148,163,184,0.2)' },
  brand: { color: '#f8fafc', fontSize: 24, fontWeight: '800' },
  brandSub: { color: '#cbd5f5', fontSize: 12, marginTop: 2, letterSpacing: 1 },
  tagline: { color: '#f8fafc', fontSize: 24, lineHeight: 32, fontWeight: '700' },
  subTagline: { color: '#dbeafe', fontSize: 14, lineHeight: 20 },
  quote: { color: '#a5b4fc', fontSize: 13, lineHeight: 18, maxWidth: 220 },

  rightPane: { flex: 0.8, minWidth: 320 },
  card: {
    borderRadius: 24,
    backgroundColor: 'rgba(15, 23, 42, 0.85)',
    padding: 24,
    borderWidth: 1,
    borderColor: 'rgba(99, 102, 241, 0.2)',
    minHeight: 560,
    position: 'relative',
    overflow: 'hidden',
  },
  cardTitle: { color: '#ffffff', fontSize: 30,fontFamily:'PlayfairDisplay_400Regular', fontWeight: '800', textAlign: 'center' },
  cardSubtitle: { color: '#e2e8f0', fontSize: 14, textAlign: 'center', marginTop: 4, marginBottom: 20 },
  stepLabel: { color: '#94a3b8', fontSize: 13, fontWeight: '600', marginBottom: 12 },

  methodRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 12 },
  methodBtn: {
    flexGrow: 1,
    minWidth: 160,
    height: 52,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.4)',
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  methodBtnActive: {
    backgroundColor: '#c4b5fd',
    shadowColor: '#c4b5fd',
    shadowOpacity: 0.45,
    shadowRadius: 18,
    shadowOffset: { width: 0, height: 10 },
  },
  methodText: { fontSize: 16, fontWeight: '600', color: '#e0e7ff' },
  methodTextActive: { fontSize: 16, fontWeight: '700', color: '#0f172a' },

  formCard: {
    marginTop: 18,
    borderRadius: 18,
    padding: 18,
    backgroundColor: 'rgba(2,6,23,0.75)',
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.25)',
    gap: 14,
  },
  formTitle: { color: '#e2e8f0', fontSize: 18, fontWeight: '700' },
  formHint: { color: '#94a3b8', fontSize: 13, lineHeight: 20 },
  recaptchaWrapper: {
    alignSelf: 'flex-start',
    padding: 6,
    borderRadius: 12,
    backgroundColor: 'rgba(15, 23, 42, 0.45)',
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.35)',
  },
  formGrid: { gap: 16 },
  inputGroup: { gap: 6 },
  label: { color: '#cbd5f5', fontSize: 13, fontWeight: '600' },

  input: {
    height: 48,
    borderRadius: 12,
    backgroundColor: '#e5e7eb',
    paddingHorizontal: 14,
    color: '#111827',
  },
  inputRow: {
    height: 48,
    borderRadius: 12,
    backgroundColor: '#e5e7eb',
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  inputField: { flex: 1, height: 48, color: '#111827' },

  validationPanel: {
    borderRadius: 16,
    padding: 16,
    backgroundColor: 'rgba(15, 23, 42, 0.6)',
    borderWidth: 1,
    borderColor: 'rgba(139, 92, 246, 0.25)',
    gap: 10,
  },
  validationTitle: { color: '#94a3b8', fontSize: 13, fontWeight: '600', letterSpacing: 1 },
  validationRow: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  validationText: { color: '#64748b', fontSize: 13 },
  validationTextPassed: { color: '#22c55e' },

  checkboxRow: { flexDirection: 'row', alignItems: 'center', gap: 12 },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: 'rgba(148, 163, 184, 0.6)',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(15, 23, 42, 0.4)',
  },
  checkboxChecked: { backgroundColor: '#c4b5fd', borderColor: '#c4b5fd' },
  checkboxLabel: { color: '#cbd5f5', flex: 1, fontSize: 13 },
  linkText: { color: '#38bdf8', textDecorationLine: 'underline', fontWeight: '600' },

  primaryButton: {
    height: 52,
    borderRadius: 16,
    backgroundColor: '#c4b5fd',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 12,
  },
  primaryButtonText: { fontSize: 16, fontWeight: '700', color: '#0f172a' },
  submitDisabled: { backgroundColor: 'rgba(148, 163, 184, 0.2)' },
  submitButton: { marginTop: 8, alignSelf: 'stretch', width: '100%' },

  errorBanner: {
    marginTop: 16,
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    padding: 12,
    borderRadius: 12,
    backgroundColor: 'rgba(248,113,113,0.12)',
    borderWidth: 1,
    borderColor: 'rgba(248,113,113,0.35)',
  },
  errorText: { color: '#fecaca', fontSize: 13, flex: 1 },

  footerHint: { color: '#64748b', fontSize: 13, textAlign: 'center', marginTop: 16 },
  altRouteRow: { top:10,flexDirection: 'row', justifyContent: 'center', alignItems: 'center', gap: 8, marginTop: 4 },
  altRouteText: { color: '#94a3b8', fontSize: 14 },
  altRouteLink: { color: '#c4b5fd', fontSize: 14, fontWeight: '600' },

  successCard: {
    borderRadius: 16,
    padding: 20,
    gap: 12,
    backgroundColor: 'rgba(15,23,42,0.6)',
    borderWidth: 1,
    borderColor: 'rgba(34,197,94,0.25)',
  },
  successTitle: { color: '#ffffff', fontSize: 20, fontWeight: '700' },
  successCopy: { color: '#cbd5f5', fontSize: 14, lineHeight: 20 },
  successWarn: { color: '#facc15', fontSize: 13 },
  successActions: { flexDirection: 'row', gap: 16, flexWrap: 'wrap' },
  primaryLink: { color: '#c4b5fd', fontWeight: '700', fontSize: 16 },
  secondaryLink: { color: '#38bdf8', fontWeight: '600', fontSize: 15 },

  hero: {
    position: 'absolute',
    right: 0,
    bottom: 0,
    width: 220,
    height: 220,
    opacity: 0.35,
  },
  glossBox: {
    position: 'absolute',
    top: 0,
    right: 0,
    bottom: 0,
    left: 0,
    borderRadius: 24,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.04)',
    pointerEvents: 'none',
  },

  homeLink: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 4 },
  homeText: { color: '#8b5cf6', fontWeight: '600' },
});

export type SignupStyles = typeof signupStyles;
